### PR TITLE
Improve 2

### PR DESCRIPTION
**Pull request by septs**
- [x] simplify editorconfig
- [x] simplify travis-ci config
- [x] simplify package.json
- [x] migrate tslint to eslint
- [x] remove unused dependency
- [x] esmodule expose
- [x] zero dependencies
- [x] smart factory
if `P` equal `unknown` then
   returns a `ThunkFunction` without params input
else
   returns a `ThunkFunction` with require params input

### CODE REVIEW

**Comment by septs** [comment]
@xdave 
```
  "dependencies": {
    "redux-thunk": "^2.3.0",
    "typescript-fsa": "^3.0.0"
  },
```

i think the two dependency, need move to peer dependency

**Comment by septs** [comment]
image
image
image

smart factory function

new feature,

My two pull requests
Each contains two break changes

I think should be iterated to `2.10.0` version

**Comment by septs** [comment]
rename generic, can make the user better understand his meaning

**Comment by xdave** [comment]
Whoa this is a big one. Reviewing.

**Comment by xdave** [comment]
I'll merge this.

**Comment by septs** [comment]
@xdave smart thunk function is a new break changes

```typescript
const foo = createAsync('foo', (input: undefined) => '');

foo // (input: undefined) => string
foo() // Expected 1 arguments, but got 0. ts(2554)
foo(undefined)

// but can be used like this

const bar = createAsync('bar', (input: string | void) => '');
bar // (input: string | void) => string
bar() // like is optional params
bar('sample')
```

**Comment by xdave** [comment]
Hmm, seeing `void` as a function argument type is weird.

**Comment by septs** [comment]
image

@xdave

**Comment by xdave** [comment]
No, that's fine... let me merge this and make the 2.10.0 release

**Pull request merged**
