### PR TITLE
Allow async actions to define the expected error type

### PR DESCRIPTION
**Pull request by safarmer**
- Added the `E` type paramter defaulting to `Error`
- Add constraint to ensure `E` is an error type
- Added tests

### CODE REVIEW

**Comment by xdave** [comment]
Sorry for not noticing this!

**Comment by xdave** [comment]
Npm release will be ready in a bit

**Comment by xdave** [comment]
Released 2.1.3 https://www.npmjs.com/package/typescript-fsa-redux-thunk/v/2.1.3

**Comment by safarmer** [comment]
Thanks for merging!

**Pull request merged**
